name: GitHub Classroom Workflow

on:
  push:
    branches: [ main ]

env:
  homework: ${{ 'SimpleJsonWriter' }}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Setup Java Environment
        run: |
          export JAVA_HOME=${{ env.JAVA_HOME }}

      - name: Cache Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Checkout Homework Repository
        uses: actions/checkout@v2

      - name: Setup Fresh Test Environment
        run: |
          git clone --depth 1 https://github.com/usf-cs212-fall2020/homework-${{ env.homework }}-template.git template
          mv -f template/${{ env.homework }}/src/test ${{ env.homework }}/src/test
          mv -f template/${{ env.homework }}/pom.xml ${{ env.homework }}/
          mvn -f ./*/pom.xml validate

      - name: Run Autograder
        uses: education/autograding@v1
